version: "3.8"

services:
  app:
    build: .
    container_name: flashcards-app
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
    stdin_open: true
    tty: true
    profiles:
      - interactive
    volumes:
      - .:/app
    working_dir: /app
    networks:
      - flashcards-network

  mongodb:
    image: mongo:7
    container_name: flashcards-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - flashcards-network

  mongo-express:
    image: mongo-express
    container_name: flashcards-mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongodb
    networks:
      - flashcards-network

volumes:
  mongodb_data:

networks:
  flashcards-network:
    driver: bridge
